.TH "AdventureAssembly.Units.Heroes.ClassModifier" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Heroes.ClassModifier
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAdventureAssembly\&.Units\&.Tests\&.TestClassModifier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApply\fP ()"
.br
.ti -1c
.RI "void \fBRemove\fP ()"
.br
.ti -1c
.RI "\fBClassModifier\fP \fBGetClone\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBRequiredCount\fP\fR [get, protected set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Units\&.Heroes\&.ClassModifier\&.Apply ()\fR [abstract]\fP"

.SS "\fBClassModifier\fP AdventureAssembly\&.Units\&.Heroes\&.ClassModifier\&.GetClone ()"

.SS "void AdventureAssembly\&.Units\&.Heroes\&.ClassModifier\&.Remove ()\fR [abstract]\fP"

.SH "Property Documentation"
.PP 
.SS "int AdventureAssembly\&.Units\&.Heroes\&.ClassModifier\&.RequiredCount\fR [get]\fP, \fR [protected set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
