.TH "AdventureAssembly.Units.Heroes.HeroIndicator" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Heroes.HeroIndicator
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
