.TH "AdventureAssembly.Interface" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Interface
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGoldInterface\fP"
.br
.ti -1c
.RI "class \fBHeroClassElement\fP"
.br
.ti -1c
.RI "class \fBHeroSelectionElement\fP"
.br
.ti -1c
.RI "class \fBHeroSelectionInterface\fP"
.br
.ti -1c
.RI "class \fBHeroSelectionStart\fP"
.br
.ti -1c
.RI "class \fBInterfaceManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
