.TH "AdventureAssembly.Units.UnitData" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.UnitData
.SH SYNOPSIS
.br
.PP
.PP
Inherits SerializedScriptableObject\&.
.PP
Inherited by \fBAdventureAssembly\&.Units\&.Enemies\&.EnemyData\fP, and \fBAdventureAssembly\&.Units\&.Heroes\&.HeroData\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "Sprite \fBSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBMaxHealth\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBUnitMovementTween\fP \fBMovementTween\fP = new \fBDefaultUnitMovementTween\fP()\fR [get]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "int AdventureAssembly\&.Units\&.UnitData\&.MaxHealth\fR [get]\fP"

.SS "\fBUnitMovementTween\fP AdventureAssembly\&.Units\&.UnitData\&.MovementTween = new \fBDefaultUnitMovementTween\fP()\fR [get]\fP"

.SS "string AdventureAssembly\&.Units\&.UnitData\&.Name\fR [get]\fP"

.SS "Sprite AdventureAssembly\&.Units\&.UnitData\&.Sprite\fR [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
