.TH "AdventureAssembly.Units.Enemies.EnemyNavigation" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Enemies.EnemyNavigation
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAdventureAssembly\&.Units\&.Enemies\&.DefaultEnemyNavigation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP (\fBEnemy\fP enemy)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Units\&.Enemies\&.EnemyNavigation\&.Update (\fBEnemy\fP enemy)\fR [abstract]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
