.TH "AdventureAssembly.Units.Modifiers.UnitModifier" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Modifiers.UnitModifier
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAdventureAssembly\&.Units\&.Modifiers\&.EnemyModifier\fP, \fBAdventureAssembly\&.Units\&.Modifiers\&.HeroModifier\fP, \fBAdventureAssembly\&.Units\&.Tests\&.DamageModifier\fP, and \fBAdventureAssembly\&.Units\&.Tests\&.HealthModifier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApply\fP (\fBUnit\fP unit)"
.br
.ti -1c
.RI "void \fBRemove\fP (\fBUnit\fP unit)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Units\&.Modifiers\&.UnitModifier\&.Apply (\fBUnit\fP unit)\fR [abstract]\fP"

.SS "void AdventureAssembly\&.Units\&.Modifiers\&.UnitModifier\&.Remove (\fBUnit\fP unit)\fR [abstract]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
