.TH "AdventureAssembly.Interface.HeroSelectionInterface" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Interface.HeroSelectionInterface
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShow\fP (List< \fBHeroData\fP > heroData)"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "void \fBShowSelections\fP (List< \fBHeroData\fP > heroData)"
.br
.ti -1c
.RI "void \fBOnHeroSelected\fP (\fBHeroData\fP heroData)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Interface\&.HeroSelectionInterface\&.Hide ()"

.SS "void AdventureAssembly\&.Interface\&.HeroSelectionInterface\&.OnHeroSelected (\fBHeroData\fP heroData)"

.SS "void AdventureAssembly\&.Interface\&.HeroSelectionInterface\&.Show (List< \fBHeroData\fP > heroData)"

.SS "void AdventureAssembly\&.Interface\&.HeroSelectionInterface\&.ShowSelections (List< \fBHeroData\fP > heroData)"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
