.TH "AdventureAssembly.Units.DamageData" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.DamageData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDamageData\fP (int baseValue)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBBaseValue\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBValue\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsCritical\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AdventureAssembly\&.Units\&.DamageData\&.DamageData (int baseValue)"

.SH "Property Documentation"
.PP 
.SS "int AdventureAssembly\&.Units\&.DamageData\&.BaseValue\fR [get]\fP"

.SS "bool AdventureAssembly\&.Units\&.DamageData\&.IsCritical\fR [get]\fP, \fR [set]\fP"

.SS "int AdventureAssembly\&.Units\&.DamageData\&.Value\fR [get]\fP, \fR [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
