.TH "AdventureAssembly.Units.Heroes.HeroStats" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Heroes.HeroStats
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdventureAssembly\&.Units\&.UnitStats\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP (\fBUnit\fP unit)"
.br
.ti -1c
.RI "float \fBGetAbilitySpeed\fP (float baseSpeed)"
.br
.in -1c

Public Member Functions inherited from \fBAdventureAssembly\&.Units\&.UnitStats\fP
.in +1c
.ti -1c
.RI "virtual \fBDamageData\fP \fBGetDamageData\fP (\fBDamageData\fP damageData)"
.br
.ti -1c
.RI "virtual int \fBGetMaxHealth\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHeroData\fP \fBHeroData\fP\fR [get, protected set]\fP"
.br
.ti -1c
.RI "\fBHero\fP \fBHero\fP\fR [get, protected set]\fP"
.br
.in -1c

Properties inherited from \fBAdventureAssembly\&.Units\&.UnitStats\fP
.in +1c
.ti -1c
.RI "\fBUnit\fP \fBUnit\fP\fR [get, protected set]\fP"
.br
.ti -1c
.RI "\fBUnitData\fP \fBUnitData\fP\fR [get, protected set]\fP"
.br
.ti -1c
.RI "\fBStat\fP< float > \fBDamageMultiplier\fP = new \fBStat\fP<float>(1f)\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBStat\fP< float > \fBMaxHealthMultiplier\fP = new \fBStat\fP<float>(1f)\fR [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float AdventureAssembly\&.Units\&.Heroes\&.HeroStats\&.GetAbilitySpeed (float baseSpeed)"

.SS "override void AdventureAssembly\&.Units\&.Heroes\&.HeroStats\&.Initialize (\fBUnit\fP unit)\fR [virtual]\fP"

.PP
Reimplemented from \fBAdventureAssembly\&.Units\&.UnitStats\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBHero\fP AdventureAssembly\&.Units\&.Heroes\&.HeroStats\&.Hero\fR [get]\fP, \fR [protected set]\fP"

.SS "\fBHeroData\fP AdventureAssembly\&.Units\&.Heroes\&.HeroStats\&.HeroData\fR [get]\fP, \fR [protected set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
