.TH "AdventureAssembly.Units.Stat< T >" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Stat< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStat\fP (T value=default)"
.br
.ti -1c
.RI "void \fBAddModifier\fP (\fBStatModifier\fP< T > modifier)"
.br
.ti -1c
.RI "void \fBRemoveModifier\fP (\fBStatModifier\fP< T > modifier)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBBaseValue\fP\fR [get]\fP"
.br
.ti -1c
.RI "T \fBValue\fP\fR [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAdventureAssembly\&.Units\&.Stat\fP< T >\&.\fBStat\fP (T value = \fRdefault\fP)"

.SH "Member Function Documentation"
.PP 
.SS "void \fBAdventureAssembly\&.Units\&.Stat\fP< T >\&.AddModifier (\fBStatModifier\fP< T > modifier)"

.SS "void \fBAdventureAssembly\&.Units\&.Stat\fP< T >\&.RemoveModifier (\fBStatModifier\fP< T > modifier)"

.SH "Property Documentation"
.PP 
.SS "T \fBAdventureAssembly\&.Units\&.Stat\fP< T >\&.BaseValue\fR [get]\fP"

.SS "T \fBAdventureAssembly\&.Units\&.Stat\fP< T >\&.Value\fR [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
