.TH "AdventureAssembly.Units.Modifiers" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Modifiers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemyModifier\fP"
.br
.ti -1c
.RI "class \fBHeroModifier\fP"
.br
.ti -1c
.RI "class \fBUnitModifier\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
