.TH "AdventureAssembly.Units.StatModifier< T >" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.StatModifier< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBProcess\fP (T value)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "T \fBAdventureAssembly\&.Units\&.StatModifier\fP< T >\&.Process (T value)\fR [abstract]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
