.TH "AdventureAssembly.Units.Abilities.SpellThiefAbility" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Abilities.SpellThiefAbility
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdventureAssembly\&.Units\&.Abilities\&.Ability\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBExecute\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBAdventureAssembly\&.Units\&.Abilities\&.Ability\fP
.in +1c
.ti -1c
.RI "void \fBExecute\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBAdventureAssembly\&.Units\&.Abilities\&.Ability\fP
.in +1c
.ti -1c
.RI "void \fBInitialize\fP (\fBHero\fP hero)"
.br
.ti -1c
.RI "void \fBOnUpdate\fP (float time)"
.br
.ti -1c
.RI "\fBAbility\fP \fBGetClone\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBAdventureAssembly\&.Units\&.Abilities\&.Ability\fP
.in +1c
.ti -1c
.RI "float \fB_currentTime\fP"
.br
.ti -1c
.RI "\fBHero\fP \fB_hero\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void AdventureAssembly\&.Units\&.Abilities\&.SpellThiefAbility\&.Execute ()\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
