.TH "AdventureAssembly.Units.Heroes.ClassData" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Heroes.ClassData
.SH SYNOPSIS
.br
.PP
.PP
Inherits SerializedScriptableObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBDescription\fP\fR [get]\fP"
.br
.ti -1c
.RI "Color \fBColor\fP\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBClassModifier\fP > \fBModifiers\fP = new List<\fBClassModifier\fP>()\fR [get]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "Color AdventureAssembly\&.Units\&.Heroes\&.ClassData\&.Color\fR [get]\fP"

.SS "string AdventureAssembly\&.Units\&.Heroes\&.ClassData\&.Description\fR [get]\fP"

.SS "List<\fBClassModifier\fP> AdventureAssembly\&.Units\&.Heroes\&.ClassData\&.Modifiers = new List<\fBClassModifier\fP>()\fR [get]\fP"

.SS "string AdventureAssembly\&.Units\&.Heroes\&.ClassData\&.Name\fR [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
