.TH "AdventureAssembly.Units.Heroes" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Heroes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClassData\fP"
.br
.ti -1c
.RI "class \fBClassManager\fP"
.br
.ti -1c
.RI "class \fBClassModifier\fP"
.br
.ti -1c
.RI "class \fBHero\fP"
.br
.ti -1c
.RI "class \fBHeroData\fP"
.br
.ti -1c
.RI "class \fBHeroDataListScriptableVariable\fP"
.br
.ti -1c
.RI "class \fBHeroIndicator\fP"
.br
.ti -1c
.RI "class \fBHeroManager\fP"
.br
.ti -1c
.RI "class \fBHeroSelectionStart\fP"
.br
.ti -1c
.RI "class \fBHeroStats\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
