.TH "AdventureAssembly.Core.TickManager" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Core.TickManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits Singleton< TickManager >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStartTickUpdates\fP ()"
.br
.ti -1c
.RI "void \fBStopTickUpdates\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBTickInterval\fP = 0\&.33333f\fR [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static Action \fBTickUpdate\fP"
.br
.ti -1c
.RI "static Action \fBTickLateUpdate\fP"
.br
.ti -1c
.RI "static Action \fBEnemyTickUpdate\fP"
.br
.ti -1c
.RI "static Action \fBEnemyTickLateUpdate\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Core\&.TickManager\&.StartTickUpdates ()"

.SS "void AdventureAssembly\&.Core\&.TickManager\&.StopTickUpdates ()"

.SH "Property Documentation"
.PP 
.SS "float AdventureAssembly\&.Core\&.TickManager\&.TickInterval = 0\&.33333f\fR [get]\fP"

.SH "Event Documentation"
.PP 
.SS "Action AdventureAssembly\&.Core\&.TickManager\&.EnemyTickLateUpdate\fR [static]\fP"

.SS "Action AdventureAssembly\&.Core\&.TickManager\&.EnemyTickUpdate\fR [static]\fP"

.SS "Action AdventureAssembly\&.Core\&.TickManager\&.TickLateUpdate\fR [static]\fP"

.SS "Action AdventureAssembly\&.Core\&.TickManager\&.TickUpdate\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
