.TH "AdventureAssembly.Units.Animation.UnitMovementTween" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Animation.UnitMovementTween
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAdventureAssembly\&.Units\&.Animation\&.DefaultUnitMovementTween\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAnimate\fP (\fBUnit\fP unit, Vector2Int newPosition, float duration)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Units\&.Animation\&.UnitMovementTween\&.Animate (\fBUnit\fP unit, Vector2Int newPosition, float duration)\fR [abstract]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
