.TH "AdventureAssembly.Units.Projectile" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Projectile
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (\fBHero\fP hero, int baseDamage, \fBUnit\fP targetUnit)"
.br
.ti -1c
.RI "void \fBInitialize\fP (\fBHero\fP hero, int baseDamage, Vector2 direction)"
.br
.ti -1c
.RI "void \fBSetMoveDirection\fP (Vector2 direction)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHero\fP \fBHero\fP\fR [get, protected set]\fP"
.br
.ti -1c
.RI "\fBUnit\fP \fBTargetUnit\fP\fR [get, protected set]\fP"
.br
.ti -1c
.RI "int \fBBaseDamage\fP\fR [get, protected set]\fP"
.br
.ti -1c
.RI "Vector2 \fBMoveDirection\fP\fR [get, protected set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Units\&.Projectile\&.Initialize (\fBHero\fP hero, int baseDamage, \fBUnit\fP targetUnit)"

.SS "void AdventureAssembly\&.Units\&.Projectile\&.Initialize (\fBHero\fP hero, int baseDamage, Vector2 direction)"

.SS "void AdventureAssembly\&.Units\&.Projectile\&.SetMoveDirection (Vector2 direction)"

.SH "Property Documentation"
.PP 
.SS "int AdventureAssembly\&.Units\&.Projectile\&.BaseDamage\fR [get]\fP, \fR [protected set]\fP"

.SS "\fBHero\fP AdventureAssembly\&.Units\&.Projectile\&.Hero\fR [get]\fP, \fR [protected set]\fP"

.SS "Vector2 AdventureAssembly\&.Units\&.Projectile\&.MoveDirection\fR [get]\fP, \fR [protected set]\fP"

.SS "\fBUnit\fP AdventureAssembly\&.Units\&.Projectile\&.TargetUnit\fR [get]\fP, \fR [protected set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
