.TH "AdventureAssembly.Interface.InterfaceManager" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Interface.InterfaceManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits Singleton< InterfaceManager >\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHeroSelectionInterface\fP \fBHeroSelectionInterface\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBHeroSelectionInterface\fP AdventureAssembly\&.Interface\&.InterfaceManager\&.HeroSelectionInterface\fR [get]\fP, \fR [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
