.TH "AdventureAssembly.Units.Enemies.EnemyStats" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Enemies.EnemyStats
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdventureAssembly\&.Units\&.UnitStats\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP (\fBUnit\fP unit)"
.br
.in -1c

Public Member Functions inherited from \fBAdventureAssembly\&.Units\&.UnitStats\fP
.in +1c
.ti -1c
.RI "virtual \fBDamageData\fP \fBGetDamageData\fP (\fBDamageData\fP damageData)"
.br
.ti -1c
.RI "virtual int \fBGetMaxHealth\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEnemyData\fP \fBEnemyData\fP\fR [get, protected set]\fP"
.br
.ti -1c
.RI "\fBEnemy\fP \fBEnemy\fP\fR [get, protected set]\fP"
.br
.in -1c

Properties inherited from \fBAdventureAssembly\&.Units\&.UnitStats\fP
.in +1c
.ti -1c
.RI "\fBUnit\fP \fBUnit\fP\fR [get, protected set]\fP"
.br
.ti -1c
.RI "\fBUnitData\fP \fBUnitData\fP\fR [get, protected set]\fP"
.br
.ti -1c
.RI "\fBStat\fP< float > \fBDamageMultiplier\fP = new \fBStat\fP<float>(1f)\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBStat\fP< float > \fBMaxHealthMultiplier\fP = new \fBStat\fP<float>(1f)\fR [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void AdventureAssembly\&.Units\&.Enemies\&.EnemyStats\&.Initialize (\fBUnit\fP unit)\fR [virtual]\fP"

.PP
Reimplemented from \fBAdventureAssembly\&.Units\&.UnitStats\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBEnemy\fP AdventureAssembly\&.Units\&.Enemies\&.EnemyStats\&.Enemy\fR [get]\fP, \fR [protected set]\fP"

.SS "\fBEnemyData\fP AdventureAssembly\&.Units\&.Enemies\&.EnemyStats\&.EnemyData\fR [get]\fP, \fR [protected set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
