.TH "AdventureAssembly.Interface.HeroClassElement" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Interface.HeroClassElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBClassData\fP \fBClassData\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBClassData\fP AdventureAssembly\&.Interface\&.HeroClassElement\&.ClassData\fR [get]\fP, \fR [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
