.TH "AdventureAssembly.Debug.DebugKeyPress" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Debug.DebugKeyPress
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBAdventureAssembly\&.Debug\&.DebugKillRandomHero\fP, and \fBAdventureAssembly\&.Debug\&.DebugOpenChest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDebugKeyPressed\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Debug\&.DebugKeyPress\&.DebugKeyPressed ()\fR [abstract]\fP"

.SS "virtual void AdventureAssembly\&.Debug\&.DebugKeyPress\&.Update ()\fR [protected]\fP, \fR [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
