.TH "AdventureAssembly.Units.Tests.DefaultStatModifier" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Tests.DefaultStatModifier
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdventureAssembly\&.Units\&.StatModifier< float >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefaultStatModifier\fP (float value=0f)"
.br
.ti -1c
.RI "override float \fBProcess\fP (float value)"
.br
.in -1c

Public Member Functions inherited from \fBAdventureAssembly\&.Units\&.StatModifier< float >\fP
.in +1c
.ti -1c
.RI "T \fBProcess\fP (T value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AdventureAssembly\&.Units\&.Tests\&.DefaultStatModifier\&.DefaultStatModifier (float value = \fR0f\fP)"

.SH "Member Function Documentation"
.PP 
.SS "override float AdventureAssembly\&.Units\&.Tests\&.DefaultStatModifier\&.Process (float value)"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
