.TH "AdventureAssembly.Units.Animation" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Animation
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDefaultUnitMovementTween\fP"
.br
.ti -1c
.RI "class \fBUnitMovementTween\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
