.TH "AdventureAssembly.Core.ExperienceManager" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Core.ExperienceManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits Singleton< ExperienceManager >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddExperience\fP (int experience)"
.br
.ti -1c
.RI "void \fBUpdateLevel\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Core\&.ExperienceManager\&.AddExperience (int experience)"

.SS "void AdventureAssembly\&.Core\&.ExperienceManager\&.UpdateLevel ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
