.TH "AdventureAssembly.Units.Tests.TestClassModifier" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Tests.TestClassModifier
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdventureAssembly\&.Units\&.Heroes\&.ClassModifier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBApply\fP ()"
.br
.ti -1c
.RI "override void \fBRemove\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBAdventureAssembly\&.Units\&.Heroes\&.ClassModifier\fP
.in +1c
.ti -1c
.RI "void \fBApply\fP ()"
.br
.ti -1c
.RI "void \fBRemove\fP ()"
.br
.ti -1c
.RI "\fBClassModifier\fP \fBGetClone\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBAdventureAssembly\&.Units\&.Heroes\&.ClassModifier\fP
.in +1c
.ti -1c
.RI "int \fBRequiredCount\fP\fR [get, protected set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void AdventureAssembly\&.Units\&.Tests\&.TestClassModifier\&.Apply ()"

.SS "override void AdventureAssembly\&.Units\&.Tests\&.TestClassModifier\&.Remove ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
