.TH "AdventureAssembly.Units.Enemies.EnemyData" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Enemies.EnemyData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdventureAssembly\&.Units\&.UnitData\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBKillExperience\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBBaseDamage\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBEnemyNavigation\fP \fBNavigation\fP = new \fBDefaultEnemyNavigation\fP()\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBAdventureAssembly\&.Units\&.UnitData\fP
.in +1c
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "Sprite \fBSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBMaxHealth\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBUnitMovementTween\fP \fBMovementTween\fP = new \fBDefaultUnitMovementTween\fP()\fR [get]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "int AdventureAssembly\&.Units\&.Enemies\&.EnemyData\&.BaseDamage\fR [get]\fP"

.SS "int AdventureAssembly\&.Units\&.Enemies\&.EnemyData\&.KillExperience\fR [get]\fP"

.SS "\fBEnemyNavigation\fP AdventureAssembly\&.Units\&.Enemies\&.EnemyData\&.Navigation = new \fBDefaultEnemyNavigation\fP()\fR [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
