.TH "AdventureAssembly.Units.Tests.TestEnemyModifier" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Tests.TestEnemyModifier
.SH SYNOPSIS
.br
.PP
.PP
Inherits SerializedMonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEnemyData\fP \fBenemyData\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBEnemyData\fP AdventureAssembly\&.Units\&.Tests\&.TestEnemyModifier\&.enemyData"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
