.TH "AdventureAssembly.Interface.HeroSelectionElement" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Interface.HeroSelectionElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerEnterHandler, IPointerExitHandler, and IPointerDownHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerExit\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerDown\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "RectTransform \fBVerticalLayoutTransform\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBHeroSelectionInterface\fP \fBHeroSelectionInterface\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBHeroData\fP \fBHeroData\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Interface\&.HeroSelectionElement\&.OnPointerDown (PointerEventData eventData)"

.SS "void AdventureAssembly\&.Interface\&.HeroSelectionElement\&.OnPointerEnter (PointerEventData eventData)"

.SS "void AdventureAssembly\&.Interface\&.HeroSelectionElement\&.OnPointerExit (PointerEventData eventData)"

.SH "Property Documentation"
.PP 
.SS "\fBHeroData\fP AdventureAssembly\&.Interface\&.HeroSelectionElement\&.HeroData\fR [get]\fP, \fR [set]\fP"

.SS "\fBHeroSelectionInterface\fP AdventureAssembly\&.Interface\&.HeroSelectionElement\&.HeroSelectionInterface\fR [get]\fP, \fR [set]\fP"

.SS "RectTransform AdventureAssembly\&.Interface\&.HeroSelectionElement\&.VerticalLayoutTransform\fR [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
