.TH "AdventureAssembly.Debug" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Debug
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebugKeyPress\fP"
.br
.ti -1c
.RI "class \fBDebugKillRandomHero\fP"
.br
.ti -1c
.RI "class \fBDebugOpenChest\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDebugInputMode\fP { \fBPress\fP, \fBHold\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAdventureAssembly\&.Debug\&.DebugInputMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPress \fP\fP
.TP
\fB\fIHold \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
