.TH "AdventureAssembly.Units.Modifiers.EnemyModifier" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Modifiers.EnemyModifier
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdventureAssembly\&.Units\&.Modifiers\&.UnitModifier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBApply\fP (\fBUnit\fP unit)"
.br
.ti -1c
.RI "void \fBApply\fP (\fBEnemy\fP enemy)"
.br
.in -1c

Public Member Functions inherited from \fBAdventureAssembly\&.Units\&.Modifiers\&.UnitModifier\fP
.in +1c
.ti -1c
.RI "void \fBApply\fP (\fBUnit\fP unit)"
.br
.ti -1c
.RI "void \fBRemove\fP (\fBUnit\fP unit)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Units\&.Modifiers\&.EnemyModifier\&.Apply (\fBEnemy\fP enemy)\fR [abstract]\fP"

.SS "override void AdventureAssembly\&.Units\&.Modifiers\&.EnemyModifier\&.Apply (\fBUnit\fP unit)"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
