.TH "AdventureAssembly.Core.TimeManager" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Core.TimeManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPause\fP ()"
.br
.ti -1c
.RI "static void \fBUnpause\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void AdventureAssembly\&.Core\&.TimeManager\&.Pause ()\fR [static]\fP"

.SS "static void AdventureAssembly\&.Core\&.TimeManager\&.Unpause ()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
