.TH "AdventureAssembly.Units.Abilities.Ability" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Abilities.Ability
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAdventureAssembly\&.Units\&.Abilities\&.ProjectileAbility\fP, and \fBAdventureAssembly\&.Units\&.Abilities\&.SpellThiefAbility\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (\fBHero\fP hero)"
.br
.ti -1c
.RI "void \fBOnUpdate\fP (float time)"
.br
.ti -1c
.RI "\fBAbility\fP \fBGetClone\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBExecute\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fB_currentTime\fP"
.br
.ti -1c
.RI "\fBHero\fP \fB_hero\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AdventureAssembly\&.Units\&.Abilities\&.Ability\&.Execute ()\fR [abstract]\fP, \fR [protected]\fP"

.SS "\fBAbility\fP AdventureAssembly\&.Units\&.Abilities\&.Ability\&.GetClone ()"

.SS "void AdventureAssembly\&.Units\&.Abilities\&.Ability\&.Initialize (\fBHero\fP hero)"

.SS "void AdventureAssembly\&.Units\&.Abilities\&.Ability\&.OnUpdate (float time)"

.SH "Member Data Documentation"
.PP 
.SS "float AdventureAssembly\&.Units\&.Abilities\&.Ability\&._currentTime\fR [protected]\fP"

.SS "\fBHero\fP AdventureAssembly\&.Units\&.Abilities\&.Ability\&._hero\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
