.TH "AdventureAssembly.Units.Heroes.HeroData" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Heroes.HeroData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdventureAssembly\&.Units\&.UnitData\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "Color \fBBackgroundColor\fP = Color\&.magenta\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBDescription\fP\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBClassData\fP > \fBClassData\fP = new List<\fBClassData\fP>()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBAbility\fP > \fBAbilities\fP = new List<\fBAbility\fP>()\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBAdventureAssembly\&.Units\&.UnitData\fP
.in +1c
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "Sprite \fBSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBMaxHealth\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBUnitMovementTween\fP \fBMovementTween\fP = new \fBDefaultUnitMovementTween\fP()\fR [get]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "List<\fBAbility\fP> AdventureAssembly\&.Units\&.Heroes\&.HeroData\&.Abilities = new List<\fBAbility\fP>()\fR [get]\fP"

.SS "Color AdventureAssembly\&.Units\&.Heroes\&.HeroData\&.BackgroundColor = Color\&.magenta\fR [get]\fP, \fR [set]\fP"

.SS "List<\fBClassData\fP> AdventureAssembly\&.Units\&.Heroes\&.HeroData\&.ClassData = new List<\fBClassData\fP>()\fR [get]\fP"

.SS "string AdventureAssembly\&.Units\&.Heroes\&.HeroData\&.Description\fR [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
