.TH "AdventureAssembly.Units" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAbilities\fP"
.br
.ti -1c
.RI "namespace \fBAnimation\fP"
.br
.ti -1c
.RI "namespace \fBEnemies\fP"
.br
.ti -1c
.RI "namespace \fBHeroes\fP"
.br
.ti -1c
.RI "namespace \fBModifiers\fP"
.br
.ti -1c
.RI "namespace \fBTests\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDamageData\fP"
.br
.ti -1c
.RI "class \fBProjectile\fP"
.br
.ti -1c
.RI "class \fBStat\fP"
.br
.ti -1c
.RI "class \fBStatModifier\fP"
.br
.ti -1c
.RI "class \fBUnit\fP"
.br
.ti -1c
.RI "class \fBUnitData\fP"
.br
.ti -1c
.RI "class \fBUnitManager\fP"
.br
.ti -1c
.RI "class \fBUnitStats\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
