.TH "AdventureAssembly.Units.Heroes.HeroDataListScriptableVariable" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Heroes.HeroDataListScriptableVariable
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableVariable< List< HeroData > >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHeroData\fP \fBGetRandom\fP ()"
.br
.ti -1c
.RI "List< \fBHeroData\fP > \fBGetRandom\fP (int count)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBHeroData\fP AdventureAssembly\&.Units\&.Heroes\&.HeroDataListScriptableVariable\&.GetRandom ()"

.SS "List< \fBHeroData\fP > AdventureAssembly\&.Units\&.Heroes\&.HeroDataListScriptableVariable\&.GetRandom (int count)"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
