.TH "AdventureAssembly.Units.Heroes.ClassManager" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Heroes.ClassManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddClassesByHeroData\fP (\fBHeroData\fP heroData)"
.br
.ti -1c
.RI "static void \fBRemoveClassesByHeroData\fP (\fBHeroData\fP heroData)"
.br
.ti -1c
.RI "static void \fBAddClass\fP (\fBClassData\fP classData)"
.br
.ti -1c
.RI "static void \fBRemoveClass\fP (\fBClassData\fP classData)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static Dictionary< \fBClassData\fP, int > \fBClassCount\fP = new Dictionary<\fBClassData\fP, int>()\fR [get]\fP"
.br
.ti -1c
.RI "static Dictionary< \fBClassData\fP, \fBClassModifier\fP > \fBClassModifiers\fP = new Dictionary<\fBClassData\fP, \fBClassModifier\fP>()\fR [get]\fP"
.br
.ti -1c
.RI "static Dictionary< \fBClassData\fP, List< \fBClassModifier\fP > > \fBClassModifierInstances\fP = new Dictionary<\fBClassData\fP, List<\fBClassModifier\fP>>()\fR [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void AdventureAssembly\&.Units\&.Heroes\&.ClassManager\&.AddClass (\fBClassData\fP classData)\fR [static]\fP"

.SS "static void AdventureAssembly\&.Units\&.Heroes\&.ClassManager\&.AddClassesByHeroData (\fBHeroData\fP heroData)\fR [static]\fP"

.SS "static void AdventureAssembly\&.Units\&.Heroes\&.ClassManager\&.RemoveClass (\fBClassData\fP classData)\fR [static]\fP"

.SS "static void AdventureAssembly\&.Units\&.Heroes\&.ClassManager\&.RemoveClassesByHeroData (\fBHeroData\fP heroData)\fR [static]\fP"

.SH "Property Documentation"
.PP 
.SS "Dictionary<\fBClassData\fP, int> AdventureAssembly\&.Units\&.Heroes\&.ClassManager\&.ClassCount = new Dictionary<\fBClassData\fP, int>()\fR [static]\fP, \fR [get]\fP"

.SS "Dictionary<\fBClassData\fP, List<\fBClassModifier\fP> > AdventureAssembly\&.Units\&.Heroes\&.ClassManager\&.ClassModifierInstances = new Dictionary<\fBClassData\fP, List<\fBClassModifier\fP>>()\fR [static]\fP, \fR [get]\fP"

.SS "Dictionary<\fBClassData\fP, \fBClassModifier\fP> AdventureAssembly\&.Units\&.Heroes\&.ClassManager\&.ClassModifiers = new Dictionary<\fBClassData\fP, \fBClassModifier\fP>()\fR [static]\fP, \fR [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
