.TH "AdventureAssembly.Units.Animation.DefaultUnitMovementTween" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdventureAssembly.Units.Animation.DefaultUnitMovementTween
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdventureAssembly\&.Units\&.Animation\&.UnitMovementTween\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAnimate\fP (\fBUnit\fP unit, Vector2Int newPosition, float duration)"
.br
.in -1c

Public Member Functions inherited from \fBAdventureAssembly\&.Units\&.Animation\&.UnitMovementTween\fP
.in +1c
.ti -1c
.RI "void \fBAnimate\fP (\fBUnit\fP unit, Vector2Int newPosition, float duration)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void AdventureAssembly\&.Units\&.Animation\&.DefaultUnitMovementTween\&.Animate (\fBUnit\fP unit, Vector2Int newPosition, float duration)"


.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
