.TH "D:/Unity/Projects/adventure-assembly/Assets/Scripts/Core Directory Reference" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Unity/Projects/adventure-assembly/Assets/Scripts/Core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBBootstrap\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConstants\&.cs\fP"
.br
.ti -1c
.RI "file \fBExperienceManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBGoldManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBTickManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBTimeManager\&.cs\fP"
.br
.in -1c
