.TH "D:/Unity/Projects/adventure-assembly/Assets/Scripts/Units/Heroes Directory Reference" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Unity/Projects/adventure-assembly/Assets/Scripts/Units/Heroes Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClassData\&.cs\fP"
.br
.ti -1c
.RI "file \fBClassManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBClassModifier\&.cs\fP"
.br
.ti -1c
.RI "file \fBHero\&.cs\fP"
.br
.ti -1c
.RI "file \fBHeroData\&.cs\fP"
.br
.ti -1c
.RI "file \fBHeroDataListScriptableVariable\&.cs\fP"
.br
.ti -1c
.RI "file \fBHeroIndicator\&.cs\fP"
.br
.ti -1c
.RI "file \fBHeroManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBHeroSelectionStart\&.cs\fP"
.br
.ti -1c
.RI "file \fBHeroStats\&.cs\fP"
.br
.in -1c
