.TH "D:/Unity/Projects/adventure-assembly/Assets/Scripts/Debug Directory Reference" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Unity/Projects/adventure-assembly/Assets/Scripts/Debug Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDebugInputMode\&.cs\fP"
.br
.ti -1c
.RI "file \fBDebugKeyPress\&.cs\fP"
.br
.ti -1c
.RI "file \fBDebugKillRandomHero\&.cs\fP"
.br
.ti -1c
.RI "file \fBDebugOpenChest\&.cs\fP"
.br
.in -1c
