.TH "D:/Unity/Projects/adventure-assembly/Assets/Scripts/Units/Modifiers/UnitModifier.cs" 3 "AdventureAssembly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Unity/Projects/adventure-assembly/Assets/Scripts/Units/Modifiers/UnitModifier.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdventureAssembly\&.Units\&.Modifiers\&.UnitModifier\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAdventureAssembly\fP"
.br
.ti -1c
.RI "namespace \fBAdventureAssembly\&.Units\fP"
.br
.ti -1c
.RI "namespace \fBAdventureAssembly\&.Units\&.Modifiers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AdventureAssembly from the source code\&.
